#!/usr/bin/env python3
"""Generate the static half of HMA-OSS's presets.

A preset in HMA-OSS is `exactPackageNames` (a set written into the app's code)
unioned with `packageNames` (what its scan added). Only the scanned half is
exported to preset_cache_v2.json, so a reader of that file sees half the preset.
This turns the written-in half into a table the tool can carry.
"""
import re
import shutil
import subprocess
import sys
from pathlib import Path


# The bare name a preset class may hold instead of a string: HMA's own package.
OWN_PACKAGE_TOKEN = 'BuildConfig.APP_PACKAGE_NAME'
RESOLVED_NAMES = ('setOf', 'listOf', 'String')


def strings_of(text: str):
    return re.findall(r'"([A-Za-z0-9_.$:-]+)"', text)


def own_package_name(src_dir: Path) -> str:
    """BuildConfig.APP_PACKAGE_NAME, read from the app's build script."""
    for parent in [src_dir, *src_dir.parents]:
        script = parent / 'build.gradle.kts'
        if not script.is_file():
            continue
        m = re.search(r'val appPackageName by extra\("([^"]+)"\)',
                      script.read_text(encoding='utf-8', errors='replace'))
        if m:
            return m.group(1)
    raise SystemExit('  \u2717 %s \u672a\u89e3\u6790\uff1a\u5f80\u4e0a\u627e\u4e0d\u5230 build.gradle.kts '
                     '\u91cc\u7684 appPackageName' % OWN_PACKAGE_TOKEN)


def extract(path: Path, own_package: str):
    """The packages of the `exactPackageNames` assignment, brace balanced.

    A bare BuildConfig name is a package too, and anything else that is not a
    string stops the run: a table that is quietly smaller than the app's preset
    hides less than the app does, which is the bug this file exists for.
    """
    src = path.read_text(encoding='utf-8', errors='replace')
    m = re.search(r'exactPackageNames\s*(?::[^=]*)?=\s*', src)
    if not m:
        return None
    rest = src[m.end():]
    head = rest.lstrip()
    if head.startswith(('setOf', 'listOf')) and '(' in head:
        i = rest.index('(')
        depth = 0
        body = rest[i:]
        for j in range(i, len(rest)):
            if rest[j] == '(':
                depth += 1
            elif rest[j] == ')':
                depth -= 1
                if depth == 0:
                    body = rest[i:j]
                    break
    else:
        # an expression, e.g. a concatenation of arrays
        end = rest.find('\n    }')
        body = rest[:end if end > 0 else 4000]
    found = strings_of(body)
    if re.search(r'\b%s\b' % re.escape(OWN_PACKAGE_TOKEN), body):
        found.append(own_package)
    leftover = re.sub(r'//[^\n]*|/\*.*?\*/', '', body, flags=re.S)
    leftover = re.sub(r'"[^"]*"', '', leftover).replace(OWN_PACKAGE_TOKEN, '')
    leftover = re.sub(r'\b(%s)\b' % '|'.join(RESOLVED_NAMES), '', leftover)
    if re.search(r'[A-Za-z_]', leftover):
        raise SystemExit('  \u2717 %s: exactPackageNames \u91cc\u6709\u672a\u89e3\u6790\u7684\u6807\u8bc6\u7b26\uff1a%s'
                         % (path.name, ' '.join(leftover.split())[:60]))
    return found


def preset_name(path: Path) -> str:
    """The NAME constant the config refers to."""
    src = path.read_text(encoding='utf-8', errors='replace')
    m = re.search(r'const val NAME\s*=\s*"([^"]+)"', src)
    return m.group(1) if m else ''


def main():
    src_dir, out_path = Path(sys.argv[1]), Path(sys.argv[2])
    own_package = own_package_name(src_dir)
    print('  %s = %s (from build.gradle.kts)' % (OWN_PACKAGE_TOKEN, own_package))
    names = {}
    for path in sorted(src_dir.glob('*Preset.kt')):
        if path.name == 'BasePreset.kt':
            continue
        cls = path.stem
        found = extract(path, own_package)
        if found is None:
            print('  %-24s exactPackageNames: 未找到（可能是纯规则 ✓）' % cls)
            continue
        uniq = sorted(set(found))
        name = preset_name(path)
        if not name:
            print('  ✗ %s 没有 NAME 常量，跳过' % cls)
            continue
        names[name] = uniq
        print('  %-20s (%-24s) %3d 个写死包名' % (name, cls, len(uniq)))

    with out_path.open('w') as out:
        out.write('// SPDX-License-Identifier: GPL-2.0\n')
        out.write('// Generated by scripts/gen_oss_presets.py -- do not edit.\n')
        out.write('//\n')
        out.write('// HMA-OSS keeps half of every preset in code (BasePreset.exactPackageNames)\n')
        out.write('// and exports only the scanned half to its cache, so a reader of the\n')
        out.write('// cache alone hides less than the app does. That half is here.\n')
        out.write('#pragma once\n\n#include <array>\n#include <string_view>\n\n')
        out.write('namespace tosya::oss_presets {\n\n')
        for cls, pkgs in names.items():
            if not pkgs:
                out.write('/* %s: no written-in names */\n'
                          'inline constexpr std::array<std::string_view, 0> k%s{};\n\n'
                          % (cls, cls))
                continue
            out.write('/* %s */\ninline constexpr std::array k%s{\n' % (cls, cls))
            for p in pkgs:
                out.write('    std::string_view{"%s"},\n' % p)
            out.write('};\n\n')
        out.write('/* The preset name each written-in set belongs to. */\n')
        out.write('struct StaticPreset {\n  std::string_view name;\n'
                  '  const std::string_view *packages;\n  std::size_t count;\n};\n\n')
        out.write('inline constexpr std::array kStatic{\n')
        for cls, pkgs in names.items():
            out.write('    StaticPreset{"%s", k%s.data(), k%s.size()},\n' % (cls, cls, cls))
        out.write('};\n\n} // namespace tosya::oss_presets\n')
    # The generated table is checked like any other source file, so it is
    # formatted here rather than left for the checker to fail on.
    fmt = shutil.which('clang-format')
    if fmt:
        subprocess.run([fmt, '-i', '--style=file', str(out_path)], check=False)
    print('  写入 %s：%d 个预设、%d 个包名（已格式化 ✓）'
          % (out_path, len(names), sum(len(v) for v in names.values())))


if __name__ == '__main__':
    main()
