// SPDX-License-Identifier: GPL-2.0
// Generated by scripts/gen_oss_presets.py -- do not edit.
//
// HMA-OSS keeps half of every preset in code (BasePreset.exactPackageNames)
// and exports only the scanned half to its cache, so a reader of the
// cache alone hides less than the app does. That half is here.
#pragma once

#include <array>
#include <string_view>

namespace tosya::oss_presets {

/* accessibility_apps: no written-in names */
inline constexpr std::array<std::string_view, 0> kaccessibility_apps{};

/* custom_rom */
inline constexpr std::array kcustom_rom{
    std::string_view{"io.chaldeaprjkt.gamespace"},
    std::string_view{"powersaver.pro"},
};

/* detector_apps */
inline constexpr std::array kdetector_apps{
    std::string_view{"at.austriao.fake_gps_detector_app"},
    std::string_view{"at.persie0.root_detection_app"},
    std::string_view{"by.sheerboy.femboydetector"},
    std::string_view{"com.AndroLua"},
    std::string_view{"com.ahmed.security_tester"},
    std::string_view{"com.android.nativetest"},
    std::string_view{"com.androidfung.drminfo"},
    std::string_view{"com.anycheck.app"},
    std::string_view{"com.atominvention.rootchecker"},
    std::string_view{"com.bryancandi.knoxcheck"},
    std::string_view{"com.byxiaorun.detector"},
    std::string_view{"com.detect.mt"},
    std::string_view{"com.dexprotector.detector.envchecks"},
    std::string_view{"com.fkjc.zcro"},
    std::string_view{"com.flinkapps.safteynet"},
    std::string_view{"com.henrikherzig.playintegritychecker"},
    std::string_view{"com.joeykrim.rootcheck"},
    std::string_view{"com.kikyps.crackme"},
    std::string_view{"com.kimchangyoun.rootbeerFresh.sample"},
    std::string_view{"com.lingqing.detector"},
    std::string_view{"com.longz.detector"},
    std::string_view{"com.rem01gaming.disclosure"},
    std::string_view{"com.reveny.nativecheck"},
    std::string_view{"com.suisho.rc"},
    std::string_view{"com.thend.integritychecker"},
    std::string_view{"com.youhu.laifu"},
    std::string_view{"com.zhenxi.hunter"},
    std::string_view{"gr.nikolasspyr.integritycheck"},
    std::string_view{"icu.nullptr.applistdetector"},
    std::string_view{"icu.nullptr.nativetest"},
    std::string_view{"id.my.pjm.qbcd_okr_dvii"},
    std::string_view{"io.github.huskydg.memorydetector"},
    std::string_view{"io.github.rabehx.securify"},
    std::string_view{"io.github.vvb2060.mahoshojo"},
    std::string_view{"io.liankong.riskdetector"},
    std::string_view{"io.ngankbakaa.lineage.detector"},
    std::string_view{"krypton.tbsafetychecker"},
    std::string_view{"luna.safe.luna"},
    std::string_view{"org.akanework.checker"},
    std::string_view{"org.matrix.demo"},
    std::string_view{"wu.Rookie.Detector"},
    std::string_view{"wu.Zygisk.Detector"},
    std::string_view{"wu.keyChain.test"},
};

/* root_apps */
inline constexpr std::array kroot_apps{
    std::string_view{"at.or.at.plugoffairplane"},
    std::string_view{"be.mygod.vpnhotspot"},
    std::string_view{"ca.mudar.fairphone.peaceofmind"},
    std::string_view{"ccc71.st.cpu"},
    std::string_view{"com.bartixxx.opflashcontrol"},
    std::string_view{"com.byyoung.setting"},
    std::string_view{"com.corphish.nightlight.generic"},
    std::string_view{"com.emanuelef.remote_capture"},
    std::string_view{"com.fox2code.mmm"},
    std::string_view{"com.franco.kernel"},
    std::string_view{"com.garyodernichts.downgrader"},
    std::string_view{"com.gitlab.giwiniswut.rwremount"},
    std::string_view{"com.hijacker"},
    std::string_view{"com.html6405.boefflakernelconfig"},
    std::string_view{"com.jhc.detach"},
    std::string_view{"com.js.nowakelock"},
    std::string_view{"com.lybxlpsv.kernelmanager"},
    std::string_view{"com.machiav3lli.backup"},
    std::string_view{"com.mayank.rucky"},
    std::string_view{"com.mrsep.ttlchanger"},
    std::string_view{"com.omarea.vtools"},
    std::string_view{"com.paget96.lsandroid"},
    std::string_view{"com.rk.taskmanager"},
    std::string_view{"com.rve.rvkernelmanager"},
    std::string_view{"com.simo.fhook"},
    std::string_view{"com.slash.batterychargelimit"},
    std::string_view{"com.softwarebakery.drivedroid"},
    std::string_view{"com.sunilpaulmathew.debloater"},
    std::string_view{"com.tester.wpswpatester"},
    std::string_view{"com.tortel.syslog"},
    std::string_view{"com.umang96.radon"},
    std::string_view{"com.valhalla.thor"},
    std::string_view{"com.zinaro.cachecleanerwidget"},
    std::string_view{"de.buttercookie.simbadroid"},
    std::string_view{"de.srlabs.snoopsnitch"},
    std::string_view{"de.tu_darmstadt.seemoo.nexmon"},
    std::string_view{"eu.roggstar.getmitokens"},
    std::string_view{"eu.roggstar.luigithehunter.batterycalibrate"},
    std::string_view{"flar2.exkernelmanager"},
    std::string_view{"id.kuato.diskhealth"},
    std::string_view{"id.xms.xtrakernelmanager"},
    std::string_view{"io.github.a13e300.ksuwebui"},
    std::string_view{"io.github.domi04151309.powerapp"},
    std::string_view{"io.github.saeeddev94.pixelnr"},
    std::string_view{"james.dsp"},
    std::string_view{"mattecarra.accapp"},
    std::string_view{"me.itejo443.bindhosts"},
    std::string_view{"me.jsonet.jshook"},
    std::string_view{"me.twrp.twrpapp"},
    std::string_view{"org.adaway"},
    std::string_view{"org.csploit.android"},
    std::string_view{"org.nuntius35.wrongpinshutdown"},
    std::string_view{"remote.hid.keyboard.client"},
    std::string_view{"ru.evgeniy.dpitunnel"},
    std::string_view{"ru.nsu.bobrofon.easysshfs"},
    std::string_view{"simple.reboot.com"},
    std::string_view{"su.sniff.cepter"},
    std::string_view{"tk.giesecke.phoenix"},
    std::string_view{"ua.polodarb.gmsflags"},
    std::string_view{"ua.polodarb.gmsflags.reborn"},
    std::string_view{"web1n.stopapp"},
    std::string_view{"whid.usb.injector"},
    std::string_view{"x1125io.initdlight"},
};

/* shizuku_dhizuku */
inline constexpr std::array kshizuku_dhizuku{
    std::string_view{"com.rosan.dhizuku"},
};

/* sus_apps */
inline constexpr std::array ksus_apps{
    std::string_view{"berserker.android.apps.sshdroid"},
    std::string_view{"cm.aptoide.pt"},
    std::string_view{"com.amaze.filemanager"},
    std::string_view{"com.anydesk.anydeskandroid"},
    std::string_view{"com.carriez.flutter_hbb"},
    std::string_view{"com.ceco.gravitybox.unlocker"},
    std::string_view{"com.devolutions.remotedesktopmanager"},
    std::string_view{"com.happymod.apk"},
    std::string_view{"com.iamaner.oneclickfreeze"},
    std::string_view{"com.lonelycatgames.Xplore"},
    std::string_view{"com.pd.pdhelper"},
    std::string_view{"com.reveny.vbmetafix.service"},
    std::string_view{"com.shamanland.privatescreenshots"},
    std::string_view{"com.speedsoftware.rootexplorer"},
    std::string_view{"me.zhanghai.android.files"},
    std::string_view{"org.connectbot"},
    std::string_view{"org.fossify.filemanager"},
};

/* xposed */
inline constexpr std::array kxposed{
    std::string_view{"org.frknkrc44.hma_oss"},
};

/* The preset name each written-in set belongs to. */
struct StaticPreset {
  std::string_view name;
  const std::string_view *packages;
  std::size_t count;
};

inline constexpr std::array kStatic{
    StaticPreset{"accessibility_apps", kaccessibility_apps.data(),
                 kaccessibility_apps.size()},
    StaticPreset{"custom_rom", kcustom_rom.data(), kcustom_rom.size()},
    StaticPreset{"detector_apps", kdetector_apps.data(), kdetector_apps.size()},
    StaticPreset{"root_apps", kroot_apps.data(), kroot_apps.size()},
    StaticPreset{"shizuku_dhizuku", kshizuku_dhizuku.data(),
                 kshizuku_dhizuku.size()},
    StaticPreset{"sus_apps", ksus_apps.data(), ksus_apps.size()},
    StaticPreset{"xposed", kxposed.data(), kxposed.size()},
};

} // namespace tosya::oss_presets
